FROM dockerfile/java:oracle-java7
MAINTAINER ronaldvaneede@gmail.com
EXPOSE 8080
CMD java -jar spring-boot-restfull-service.jar
ADD build/spring-boot-restfull-service.jar /data/spring-boot-restfull-service.jar